services:
  stats-server:
    build: ./stat_svc/http_service
    image: stat_app
    container_name: stat_app
    ports:
      - "9090:9090"

  stats-db:
    image: postgres:16.1

  ewm-service:
    build: ./main_svc
    image: main_app
    container_name: main_app
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:16.1
